config/routes.rb
Rails.application.routes.draw do

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  devise_for :users
  resources :users do
    resources :minors
  end
  resources :employers  

  resources :schools

  

  root 'static_pages#index'

  match '/camera', to: 'headshot_demo#index', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    redirect_to user_path(current_user.id) if user_signed_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="row">
  <!-- <div class="col-lg-2 col-sm-1">Left Side</div> -->
  <div class="col-lg-8 col-sm-10 span8 offset2">
    <div class="page-header work-permit">
    <h1>Applying for a work permit?</h1>
    </div>
  
    <div class="hero-unit content">
    <%= image_tag("three-students-smiling.jpg", class: 'thumbnail three-students') %>
    <h3>The following students do NOT need work permits:</h3>
      <ul>
        <li>Those who have graduated from high school, regardless of age</li>
        <li>Those who have passed the California High School Proficiency Examination</li>
        <li>Those who are 18 years of age or older</li>
      </ul>
    </div>
<!--     <h3>To apply, please enter your date of birth or %= link_to "sign in", new_minor_session_path %> to continue</h3> -->
  </div>
  <!-- <div class="col-lg-2 col-sm-1">Right Side</div> -->
</div>

<div class="row">
<!-- <div class="container"> -->
  <div class="col-lg-4 col-sm-1"></div>
  <div class="col-lg-4 col-sm-10 span8 offset2 work-submit">

  <%= link_to 'Apply for work form', new_user_registration_path, class: 'btn btn-warning btn-block' %>
  </div>
  <br>
  <div class="col-lg-4 col-sm-1"></div>
<!-- </div> -->
</div>