config/routes.rb
Rails.application.routes.draw do

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  devise_for :users
  resources :users do
    resources :minors
  end
  resources :employers  

  resources :schools

  

  root 'static_pages#index'

  match '/camera', to: 'headshot_demo#index', via: 'get'

end

app/models/minor.rb
class Minor < ActiveRecord::Base
  belongs_to :user
  has_one :minor_address
end

app/controllers/minors_controller.rb
class MinorsController < ApplicationController
  before_action :set_minor, only: [ :show, :edit, :update, :destroy]
  before_action :get_current_user
  before_action :populate_grade, only: [:new, :edit]

  # GET /minors
  # GET /minors.json
  def index
    # @minor = @user.minors.all
    redirect_to user_path(@user.id)
  end

  # GET /minors/1
  # GET /minors/1.json
  def show
    @minor = @user.minors.find(params[:id])
  end

  # GET /minors/new
  def new
    @minor = @user.minors.new
  end

  # GET /minors/1/edit
  def edit
  end

  # POST /minors
  # POST /minors.json
  def create
    @minor = @user.minors.new(minor_params)

    respond_to do |format|
      if @minor.save
        format.html { render :show, notice: 'Minor was successfully created.' }
        format.json { render :show, status: :created, location: @minor }
      else
        format.html { render :new }
        format.json { render json: @minor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minors/1
  # PATCH/PUT /minors/1.json
  def update
    respond_to do |format|
      if @minor.update(minor_params)
        format.html { redirect_to :show, notice: 'Minor was successfully updated.' }
        format.json { render :show, status: :ok, location: @minor }
      else
        format.html { render :edit }
        format.json { render json: @minor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minors/1
  # DELETE /minors/1.json
  def destroy
    @minor.destroy
    respond_to do |format|
      format.html { redirect_to minors_url, notice: 'Minor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_minor
      @minor = @user.minors.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def get_current_user
      @user = User.find(params[:user_id])
      # @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minor_params
      params.require(:minor).permit(:first_name, :last_name, :ssn, :dob, :grade)
    end

    def populate_grade
      @grades = [5,6,7,8,9,10,11,12,"n/a"]
    end
end

app/helpers/minors_helper.rb
module MinorsHelper

  def current_minor?(minor)
    minor == current_minor
  end

end

app/views/minors/_form.html.erb
<%= form_for [current_user, @minor], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ssn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ssn, :class => 'text_field' %> <i>(format 123-12-1234)</i>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dob, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dob, :class => 'text_field' %> <i>(format: mm-dd-yyyy)</i>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :grade, :class => 'control-label' %>
    <div class="controls">
      <!-- %= f.text_field :grade, :class => 'text_field' %> -->
      <%= f.collection_select :grade, @grades, :to_s, :to_s, include_blank: true %>
    </div>
  </div>


  <!-- <div class="control-group">
    <! %= f.label :age, :class => 'control-label' %> -->
    <!--<div class="controls">
      %= f.text_field :age, readonly: true, type: "hidden", :class => 'text_field' %>
    </div>
  </div> -->
  <div class="form-actions">
    <%= f.submit "Submit", :class => 'btn btn-primary span2' %>  
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_minors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/minors/edit.html.erb
<%- model_class = Minor -%>
<div class="span8 offset3">
<div class="page-header">
  <!-- <h1>%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1> -->
  <h1>Edit <%= current_minor.first_name.titleize %>'s Account</h1>
</div>
<%= render :partial => 'form' %>

</div>

app/views/minors/index.html.erb
<%- model_class = Minor -%>
<div class="page-header">
  <!-- <h1>%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1> -->
  <h1>Students</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:ssn) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:grade) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @minors.each do |minor| %>
      <tr>
        <td><%= link_to minor.id, minor_path(minor) %></td>
        <td><%= minor.first_name %></td>
        <td><%= minor.last_name %></td>
        <td><%= minor.ssn %></td>
        <td><%= minor.dob %></td>
        <td><%= minor.age %></td>
        <td><%= minor.grade %></td>
        <td><%=l minor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_minor_path(minor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      minor_path(minor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_minor_path,
            :class => 'btn btn-primary' %>

app/views/minors/new.html.erb
<h1>New minor</h1>

<%= render 'form' %>

<%= link_to 'Back', user_minors_path %>

app/views/minors/show.html.erb
<%- model_class = Minor -%>
<div class="span8 offset3">
<div class="page-header">
  <!-- <h1>%=t '.title', :default => model_class.model_name.human.titleize %></h1> -->
  <h1><%= current_minor.first_name.titleize %>'s Profile</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @minor.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @minor.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ssn) %>:</strong></dt>
  <dd><%= @minor.ssn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @minor.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @minor.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:grade) %>:</strong></dt>
  <dd><%= @minor.grade %></dd>
</dl>

<div class="form-actions center_it">
  <!-- %= link_to t('.back', :default => t("helpers.links.back")),
              minors_path, :class => 'btn'  %> -->
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_minor_path(@minor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              minor_path(@minor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @minor.first_name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @minor.last_name %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @minor.ssn %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @minor.dob %>
</p>

<p>
  <strong>Age:</strong>
  <%= @minor.age %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @minor.grade %>
</p>

<%= link_to 'Edit', edit_user_minor_path(current_user.id, @minor.id) %> |
<%= link_to 'Back', user_minors_path %>